name: Summarize new issues

on:
  issues:
    types: [opened]
  issue_comment:

jobs:
  summary:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      models: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run AI Inference
        uses: actions/github-script@v7
        id: inference
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          result-encoding: string
          script: |
            const ai = require("./.github/scripts/ai/dist/prompt.js");

            console.log(context.event.issue);

            return await ai(`# ${context.event.issue.title}\n${context.event.issue.body}`)

      - name: Comment with AI summary
        run: |
          gh issue comment $ISSUE_NUMBER --body '${{ steps.inference.outputs.result }}'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
