name: Summarize new issues

on:
  issues:
    types: [opened]
  issue_comment:

jobs:
  summary:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      models: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run AI Inference
        uses: actions/github-script@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USER: ${{ github.event.issue.user.login }}
        with:
          script: |
            const ai = await import("${{ github.workspace }}/.github/scripts/ai/dist/prompt.js");

            const issue = context.payload.issue;

            console.log(JSON.stringify(issue.title, null, 2));

            const resp = await ai.handle(`# ${issue.title}\n ${issue.body}`)

            const [owner, repo] = "${{ github.repository }}".split("/");
            const issue_number = ${{ github.event.issue.number }};

            if (resp.warn.length > 0) {
              await github.rest.issues.createComment({
                owner,
                repo, 
                issue_number,
                body: `**Detected as ${resp.spam ? "spammer" : "disrespectedful behaviour"}**\n\n${resp.warn}`.replace(/@user/g, `@${issue.user.login}`),
              });
            }

            if (resp.toneInfo.length > 0) {
              await github.rest.issues.createComment({
                owner,
                repo, 
                issue_number,
                body: resp.toneInfo.replace(/@user/g, `@${issue.user.login}`),
              });
            }

            if (resp.summary > 0) {
              await github.rest.issues.createComment({
                owner,
                repo, 
                issue_number,
                body: resp.summary,
              });
            }

            const { id: comment_id } = await github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body: JSON.stringify(resp, null, 4)
            });


            await github.rest.issues.updateComment({
              owner,
              repo,
              comment_id,
              body: "_Mods logs are here_"
            });
