name: Summarize new issues

on:
  issues:
    types: [opened]
  issue_comment:

jobs:
  summary:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      models: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run AI Inference
        uses: actions/github-script@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const ai = await import("${{ github.workspace }}/.github/scripts/ai/dist/prompt.js");

            console.log(JSON.stringify(context.payload.issue.title, null, 2));

            const resp = await ai.handle(`# ${context.payload.issue.title}\n ${context.payload.issue.body}`)

            if (resp.warn.length > 0) {
              const [owner, repo] = "${{ github.repository }}".split("/");

              await octokit.rest.issues.createComment({
                owner,
                repo, 
                issue_number: ${{ github.event.issue.number }},
                body: `**Detected as ${resp.spam ? "spammer" : "disrespectedful behaviour"}**\n\n${resp.warn}`,
              });
            }
